### ISSUE TITLE
[Feature request] Add support for HashLink

### ISSUE THREAD

**Issue by cedx** [krdlab/setup-haxe#6]
[HashLink](https://hashlink.haxe.org) was created to become the new default VM for Haxe.
It would be very cool if this action allow to also download and setup HashLink.

Probably easy to implement for Windows environments, as Windows releases are "officially" supported:
https://github.com/HaxeFoundation/hashlink/releases

For Linux and macOS, it would be much more difficult: you need to install the required dependencies, and `make all` + `make install` 😢 (cf. https://github.com/HaxeFoundation/hashlink/wiki/Building-and-Installing)

**Comment by PXshadow** [comment]
Hashlink is now in homebrew, only linux left for manual installation.

**Comment by PXshadow** [comment]
@cedx I wrote up a github action to setup hashlink only perhaps it could be plugged into setup-haxe and other tools https://github.com/pxshadow/setup-hashlink

**Comment by cedx** [comment]
I guess we can close this issue, now that there is a dedicated action to setup Hashlink.
